ProjectTAMA/Controllers/PlaceTablesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjectTAMA.Models;

namespace ProjectTAMA.Controllers
{
    public class PlaceTablesController : Controller
    {
        private PlacesInfoDatabaseEntities db = new PlacesInfoDatabaseEntities();

        // GET: PlaceTables
        public ActionResult Index()
        {
            return View(db.PlaceTables.ToList());
        }

        // GET: PlaceTables/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PlaceTable placeTable = db.PlaceTables.Find(id);
            if (placeTable == null)
            {
                return HttpNotFound();
            }
            return View(placeTable);
        }

        // GET: PlaceTables/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PlaceTables/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PlaceID,PlaceName,PlaceDescription,PlaceImage")] PlaceTable placeTable)
        {
            if (ModelState.IsValid)
            {
                db.PlaceTables.Add(placeTable);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(placeTable);
        }

        // GET: PlaceTables/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PlaceTable placeTable = db.PlaceTables.Find(id);
            if (placeTable == null)
            {
                return HttpNotFound();
            }
            return View(placeTable);
        }

        // POST: PlaceTables/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PlaceID,PlaceName,PlaceDescription,PlaceImage")] PlaceTable placeTable)
        {
            if (ModelState.IsValid)
            {
                db.Entry(placeTable).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(placeTable);
        }

        // GET: PlaceTables/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PlaceTable placeTable = db.PlaceTables.Find(id);
            if (placeTable == null)
            {
                return HttpNotFound();
            }
            return View(placeTable);
        }

        // POST: PlaceTables/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PlaceTable placeTable = db.PlaceTables.Find(id);
            db.PlaceTables.Remove(placeTable);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProjectTAMA/Views/PlaceTables/Create.cshtml
@model ProjectTAMA.Models.PlaceTable

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@*@using (Html.BeginForm())*@
@using (Html.BeginForm("Create", "PlaceTables", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>PlaceTable</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.PlaceName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PlaceName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PlaceName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PlaceDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PlaceDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PlaceDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PlaceImage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PlaceImage, new { Type = "file" })
                <input name="PlaceDescription" class="form-control text-box single-line" id="PlaceDescription" type="file" value="">
                @Html.ValidationMessageFor(model => model.PlaceImage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ProjectTAMA/Views/PlaceTables/Delete.cshtml
@model ProjectTAMA.Models.PlaceTable

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PlaceTable</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PlaceName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PlaceName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PlaceDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PlaceDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PlaceImage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PlaceImage)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ProjectTAMA/Views/PlaceTables/Details.cshtml
@model ProjectTAMA.Models.PlaceTable

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>PlaceTable</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PlaceName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PlaceName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PlaceDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PlaceDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PlaceImage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PlaceImage)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.PlaceID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ProjectTAMA/Views/PlaceTables/Edit.cshtml
@model ProjectTAMA.Models.PlaceTable

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>PlaceTable</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.PlaceID)

    <div class="form-group">
        @Html.LabelFor(model => model.PlaceName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PlaceName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PlaceName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PlaceDescription, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PlaceDescription, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PlaceDescription, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
        @Html.LabelFor(model => model.PlaceImage, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PlaceImage, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PlaceImage, "", new { @class = "text-danger" })
        </div>
    </div>*@
    <div class="form-group">
        @Html.LabelFor(model => model.PlaceImage, htmlAttributes: new { @class = "control-label col-md-2" })
    </div>
    <div class="col-md-10">
        @Html.EditorFor(model => model.PlaceImage, new { htmlAttributes = new { @class = "form-control" } ,Type="file"})
        @Html.ValidationMessageFor(model => model.PlaceImage, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ProjectTAMA/Views/PlaceTables/Index.cshtml
@model IEnumerable<ProjectTAMA.Models.PlaceTable>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PlaceName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PlaceDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PlaceImage)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.PlaceName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PlaceDescription)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PlaceImage)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.PlaceID }) |
            @Html.ActionLink("Details", "Details", new { id=item.PlaceID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.PlaceID })
        </td>
    </tr>
}

</table>