ProjectTAMA/Models/PlaceTable.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTAMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlaceTable
    {
        public int PlaceID { get; set; }
        public string PlaceName { get; set; }
        public string PlaceDescription { get; set; }
        public byte[] PlaceImage { get; set; }
    }
}

ProjectTAMA/Controllers/PlacesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjectTAMA.Models;
using System.Data.SqlClient;
using System.Configuration;
using System.Data;
using System.Net;

namespace ProjectTAMA.Controllers
{
    public class PlacesController : Controller
    {
        PlacesInfoDatabaseEntities1 _db = new PlacesInfoDatabaseEntities1();
        // GET: Places
        public ActionResult Index()
        {

            List<PlaceDescriptionViewModel> placeDesViewMdl = new List<PlaceDescriptionViewModel>();
            List<PlaceDescriptionTable> placeDesTbl = _db.PlaceDescriptionTables.ToList();
            foreach (var item in placeDesTbl)
            {
                PlaceDescriptionViewModel placeDes = new PlaceDescriptionViewModel();
                placeDes.ID = item.ID;
                placeDes.PlaceName = item.PlaceName;
                placeDes.PlaceDescription = item.PlaceDescription;
                placeDes.Difficulty = item.Difficulty;
                placeDes.TimeOfVisit = item.TimeOfVisit;
                placeDes.HotelsAvailable = item.HotelsAvailable;

                placeDesViewMdl.Add(placeDes);


            }
            return View(placeDesViewMdl);

            //return View();
        }


        //placeDetail Info

        public ActionResult PlaceDetail(int? id)
        {
            List<PlaceDescriptionViewModel> placeDesViewMdl = new List<PlaceDescriptionViewModel>();
            List<PlaceDescriptionTable> placeDesTbl = _db.PlaceDescriptionTables.ToList();

            PlaceDescriptionTable placeDescriptionTable = _db.PlaceDescriptionTables.Find(id);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (placeDescriptionTable == null)
            {
                return HttpNotFound();
            }

           
                PlaceDescriptionViewModel placeDes = new PlaceDescriptionViewModel();
                placeDes.ID = placeDescriptionTable.ID;
                placeDes.PlaceName = placeDescriptionTable.PlaceName;
                placeDes.PlaceDescription = placeDescriptionTable.PlaceDescription;
                placeDes.Difficulty = placeDescriptionTable.Difficulty;
                placeDes.TimeOfVisit = placeDescriptionTable.TimeOfVisit;
                placeDes.HotelsAvailable = placeDescriptionTable.HotelsAvailable;

                //placeDesViewMdl.Add(placeDes);


           
            return View(placeDes);
            //return View();
        }

        public ActionResult Create()
        {
            return View();
        }

      
    }
}

ProjectTAMA/Views/Places/Index.cshtml
@model IEnumerable<ProjectTAMA.Models.PlaceDescriptionViewModel>
<body>
    <div class="colorlib-wrap">
        <div class="container">
            <div class="row">
                <div class="col-md-9">
                    <div class="row">
                        <div class="wrap-division">
                            @foreach (var item in Model)
                            {

                                <div class="col-md-6 col-sm-6 animate-box">
                                    <div class="hotel-entry">
                                        <a href="@Url.Action("PlaceDetail", "Places",new { id = item.ID })" class="hotel-img" style="background-image: url(PlaceImages/@item.TimeOfVisit);">
                                            @*<img src="@Url.Content("~/PlaceImages/"+@item.TimeOfVisit) "/>*@
                                            @*<p>@Html.DisplayFor(modelItem => item.TimeOfVisit)</p>*@

                                        </a>
                                        <div class="desc">
                                            @if (item.Difficulty == 1)
        {
                                    <p class="star"><span><i class="icon-star-full"></i><i class="icon-star-empty"></i><i class="icon-star-empty"></i><i class="icon-star-empty"></i><i class="icon-star-empty"></i></span>Difficulty Level </p>
}
                                            @if (item.Difficulty == 2)
        {
                                    <p class="star"><span><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-empty"></i><i class="icon-star-empty"></i><i class="icon-star-empty"></i></span>Difficulty Level </p>
}
                                            @if (item.Difficulty == 3)
        {
                                    <p class="star"><span><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-empty"></i><i class="icon-star-empty"></i></span>Difficulty Level </p>
}
                                            @if (item.Difficulty == 4)
        {
                                    <p class="star"><span><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-empty"></i></span>>Difficulty Level </p>
}
                                            @if (item.Difficulty == 5)
        {
                                    <p class="star"><span><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i></span>>Difficulty Level </p>
}
                                            <h3><a href="hotel-room.html">@Html.DisplayFor(modelItem => item.PlaceName)</a></h3>
                                            <span class="place"></span>
                                            @*<p>@Html.DisplayFor(modelItem => item.PlaceDescription)</p>*@
                                        </div>
                                    </div>
                                </div>



                                @*<div class="col-md-6 col-sm-6 animate-box">
                                        <div class="hotel-entry">
                                            <a href="hotel-room.html" class="hotel-img" style="background-image: url(images/hotel-2.jpg);">
                                                <p class="price"><span>$120</span><small> /night</small></p>
                                            </a>
                                            <div class="desc">
                                                <p class="star"><span><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i></span> 545 Reviews</p>
                                                <h3><a href="hotel-room.html">Hotel Edison</a></h3>
                                                <span class="place">New York, USA</span>
                                                <p>A small river named Duden flows by their place and supplies it with the necessary regelialia.</p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-sm-6 animate-box">
                                        <div class="hotel-entry">
                                            <a href="hotel-room.html" class="hotel-img" style="background-image: url(images/hotel-3.jpg);">
                                                <p class="price"><span>$120</span><small> /night</small></p>
                                            </a>
                                            <div class="desc">
                                                <p class="star"><span><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i></span> 545 Reviews</p>
                                                <h3><a href="hotel-room.html">Hotel Edison</a></h3>
                                                <span class="place">New York, USA</span>
                                                <p>A small river named Duden flows by their place and supplies it with the necessary regelialia.</p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-sm-6 animate-box">
                                        <div class="hotel-entry">
                                            <a href="hotel-room.html" class="hotel-img" style="background-image: url(images/hotel-4.jpg);">
                                                <p class="price"><span>$120</span><small> /night</small></p>
                                            </a>
                                            <div class="desc">
                                                <p class="star"><span><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i></span> 545 Reviews</p>
                                                <h3><a href="hotel-room.html">Hotel Edison</a></h3>
                                                <span class="place">New York, USA</span>
                                                <p>A small river named Duden flows by their place and supplies it with the necessary regelialia.</p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-sm-6 animate-box">
                                        <div class="hotel-entry">
                                            <a href="hotel-room.html" class="hotel-img" style="background-image: url(images/hotel-5.jpg);">
                                                <p class="price"><span>$120</span><small> /night</small></p>
                                            </a>
                                            <div class="desc">
                                                <p class="star"><span><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i></span> 545 Reviews</p>
                                                <h3><a href="hotel-room.html">Hotel Edison</a></h3>
                                                <span class="place">New York, USA</span>
                                                <p>A small river named Duden flows by their place and supplies it with the necessary regelialia.</p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-sm-6 animate-box">
                                        <div class="hotel-entry">
                                            <a href="hotel-room.html" class="hotel-img" style="background-image: url(images/hotel-6.jpg);">
                                                <p class="price"><span>$120</span><small> /night</small></p>
                                            </a>
                                            <div class="desc">
                                                <p class="star"><span><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i></span> 545 Reviews</p>
                                                <h3><a href="hotel-room.html">Hotel Edison</a></h3>
                                                <span class="place">New York, USA</span>
                                                <p>A small river named Duden flows by their place and supplies it with the necessary regelialia.</p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-sm-6 animate-box">
                                        <div class="hotel-entry">
                                            <a href="hotel-room.html" class="hotel-img" style="background-image: url(images/hotel-7.jpg);">
                                                <p class="price"><span>$120</span><small> /night</small></p>
                                            </a>
                                            <div class="desc">
                                                <p class="star"><span><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i></span> 545 Reviews</p>
                                                <h3><a href="hotel-room.html">Hotel Edison</a></h3>
                                                <span class="place">New York, USA</span>
                                                <p>A small river named Duden flows by their place and supplies it with the necessary regelialia.</p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-sm-6 animate-box">
                                        <div class="hotel-entry">
                                            <a href="hotel-room.html" class="hotel-img" style="background-image: url(images/hotel-8.jpg);">
                                                <p class="price"><span>$120</span><small> /night</small></p>
                                            </a>
                                            <div class="desc">
                                                <p class="star"><span><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i></span> 545 Reviews</p>
                                                <h3><a href="hotel-room.html">Hotel Edison</a></h3>
                                                <span class="place">New York, USA</span>
                                                <p>A small river named Duden flows by their place and supplies it with the necessary regelialia.</p>
                                            </div>
                                        </div>
                                    </div>*@
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
</body>

ProjectTAMA/Views/Places/PlaceDetail.cshtml
@model ProjectTAMA.Models.PlaceDescriptionViewModel



<div class="colorlib-wrap">
    <div class="container">
        <div class="row">
            <div class="col-md-9">
                <div class="row">
                    <div class="col-md-12">
                        <div class="wrap-division">
                            <div class="col-md-12 col-md-offset-0 heading2 animate-box">
                                <h2>@Model.PlaceName</h2>
                            </div>
                            <div class="row">
                                <div class="col-md-12 animate-box">
                                    <div class="room-wrap">
                                        <div class="row">
                                            <div class="col-md-6 col-sm-6">

                                                @*<div class="room-img" style="background-image: url(PlaceImages/Annapurna.jpeg);"></div>*@
                                                <img src="~/PlaceImages/@Model.TimeOfVisit"  height="400" width="420">

                                            </div>
                                            <div class="col-md-6 col-sm-6">
                                                <div class="desc">
                                                    <h2>Place Detail</h2>
                                                    @*<p class="price"><span>$45</span> <small>/ night</small></p>*@
                                                    <p>@Model.PlaceDescription</p>
                                                    <p><a href="#" class="btn btn-primary">View Map</a></p>

                                                    <h3>Number of hotels: @Model.HotelsAvailable</h3>
                                                    <!--side Bar-->
                                                    <div class="col-md-3">
                                                        <div class="sidebar-wrap">
                                                            <div class="side animate-box">
                                                                <div class="row">
                                                                    <div class="col-md-12">
                                                                        <h3 class="sidebar-heading">Difficulty Level</h3>
                                                                        <form method="post" class="colorlib-form-2">
                                                                            @if (Model.Difficulty == 1)
                            {
                                                <p class="star"><span><i class="icon-star-full"></i><i class="icon-star-empty"></i><i class="icon-star-empty"></i><i class="icon-star-empty"></i><i class="icon-star-empty"></i></span> </p>
}
                                                                            @if (Model.Difficulty == 2)
                            {
                                                <p class="star"><span><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-empty"></i><i class="icon-star-empty"></i><i class="icon-star-empty"></i></span> </p>
}
                                                                            @if (Model.Difficulty == 3)
                            {
                                                <p class="star"><span><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-empty"></i><i class="icon-star-empty"></i></span></p>
}
                                                                            @if (Model.Difficulty == 4)
                            {
                                                <p class="star"><span><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-empty"></i></span> </p>
}
                                                                            @if (Model.Difficulty == 5)
                            {
                                                <p class="star"><span><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i></span> </p>
}
                                                                        </form>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>

                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>